language: python
before_script:
  - chmod +x semantic_release.sh && ./semantic_release.sh
script:
  - chmod +x build.sh && ./build.sh
  - chmod +x assets_release.sh && ./assets_release.sh
deploy:
  skip_cleanup: true
  provider: packagecloud
  repository: "develop"
  username: "twine"
  token:
    secure: "${PACKAGECLOUD_TOKEN}"
  dist: "python"
  local-dir: src/dist
  on:
    all_branches: true
after_deploy:
  skip_cleanup: true
  provider: script

env:
  global:
      - secure: pB6cyUl6DW5hZA4EicWm02OTj4q/SV1Ivj/9qaCHKlokhdfUPcXVuOvX5Vh4fvr6ub+y3GlXuDCBDqDTJlrotW6V0UKqC5dzfexVH/5n6jBL+P/n5mB8GjjRzmAJmgAEWaa8WjC2J2JCh1cUMo3rs/AHDdYEdtVS0Ef+dv86M105pr4RrE1fRMQhQ/5FbXGCe61Zb13OL7xtS1Wy4QjRwISXHnGXh4kb$
      - secure: jh8XovyWBPqEc+EUnAQ7RyTstJOlPr+0Dec56RXeo8/lT6YIhLX3zh2Mas5m4+XV51TxQpP9jxRwEWSXCW90RMsFNlc5MRvfKwbCwTJtEgyIkCej1ovp9DL3vF1N+M8DB9bMdKFrDpnHdEbSTFkj4dFz18JCiem30tTX+gW4PsqN52LkS56FNybE6iB5XTc/IrZ+wZ3h/W8Nb0qekBvryXlHgDyDjEQk$
