language: python
install:
  - gem install package_cloud
before_script:
  - semantic_release.sh
script:
  - build.sh
deploy:
  - provider: script
    script: deploy.sh
    on:
      all_branches: true
env:
  global:
    secure: TBQlC0jbJOpi0dwiA0zHd6R7plgvsVhOSuqlMBvwsFu+BE7gjJCrDHWpoPxvp9whfIM2P9uKlQW29kgV3UKUSYO/1PgVGhM41f/cGU7tRnfSZ+kqh4J8v7AuYbcnn9QTrJ6Ue/qbUJwV6x/qRlFELC2HStAPRJIZ505FImkNNRB1RT8UOK03T7keMeqao14sRyCeH2qOm2gDjP/fFbfWp42kqdv5wyqD+FnYsY7ku3PZn8CIiP8nkZKTUmalsdXUktWlVpWnK1RVB+tD5L52dgVYlN/qIm/s2AZGGPsJ2+nwPNKuCO3mF0BPRd73T4JrpWQFHmdmJerlmQ5PwGVk7Lj1TkAQL691NM1Y6//sq38HDfvfnE5Uvxo/YQUtFNJjaU7ZtoHUlVCLk2GInCBZqMikh0Y77eNty4ZMTSXrwTRd7L5CDLaFj0cLwKa/0j6qcY8gYgRT9qpJP/1MJZOLRLunywkiyafS1GR+Lmq2D/7iQottc8aRKLWETZOS5FWGSvkTtJSbfqIN03JQysJ86YZioszJQjLUMZf6bIiZnzuBV7ad+WGGQ610my/la3OpY6EoJLdCTjeM7NF8GhZvdmsu5+PMZ5RoxSf/BNrYvPvg54ASiu6JXn5YJbikR+WbO/z0Fs8wci4IJYPCuutuEh2DyiMy3WwfBejOcnj8TWE=


# deploy:
#   skip_cleanup: true
#   provider: packagecloud
#   repository: "develop"
#   username: "twine"
#   token:
#     secure: SGzKPKI2BlHI2bqv4DTB1DikED2WmNxYBfcmot2dKaFJ2pZ5Vcy2FSJUKfpSM80DqHQj0R1+uAz2sSirXd1HE/iYAXfejwUGbYWQXy59e9UIbHKi61/2Vx4lscNr3w1sfNbHiExvqWc9K6P+yAq42rf9dfE1UiGjk3x4PzuOCzHjxav/NtoMiVGBSNZZfZdCHER5UxL4dNyEgCpZc+jjh0zDhUM1VBg0SDh6ZVLe58+Y8sOWyzBdkJV2QOL103HsYJ6vMXjAI4JnMIgY9h6xTaJ2GlTxk22NnN17Wih15wvoqWbWAwujGZq/QpBmiLcSMh1/1ZMY4l1RFKSRj0z9kwbg09GPR/2lmWHKAZLja+QH0bh4OcUbOPILasgyQl7LZt4lqKDI/dpCEiPQpWpLrPsR+TlL9Lf/x6bNIugHMuQ312fJUfjh4winKp21uiavUdavTA4XQxVRzdxYToVRqC4ONHLg+ZeclENwdszGzZ+AMj84Y1sje3uqwXJQ2w9bFM1F+Mgo9SLjYowHnhlv7kc9oJmLrLpFGyYR+iiVQgyPS1lpxYY2j4qvAe5fhJfc53jkSFA7ekyqw071FV2PGXeVUxcGE+VHmBPIrXbh0wtBIkwcuOuzjQI9IK8m4DZmttRa8BvSTZbdZAWM0gM9Iz+jDSHMiouUL8srugQiIxI=
#   dist: "python"
#   local-dir: src/dist
#   on:
#     all_branches: true