language: python
before_script:
  - chmod +x semantic_release.sh && ./semantic_release.sh
script:
  - chmod +x build.sh && ./build.sh
deploy:
  skip_cleanup: true
  provider: packagecloud
  repository: "develop"
  username: "twine"
  token:
    secure: "${PACKAGECLOUD_TOKEN}"
  dist: "python"
  local-dir: src/dist
  on:
    all_branches: true
env:
  global:
    secure: URvQGYN1Z22mAchX3S+ker+c8hJD6E63AAA6t4gkBAxql3h8/EfleS6+y0XXgFd8boCcEMwWuKmat1iA+zesBoMMNoITRHWl53T5/SC9yKEfSg0HQRy0RYPdmkhFcQncqw0enMpeOniMb6lkLM2CnIfitMjnb0ieJwrsdOhS7Ru0AOwqzpGhJRtc6Eusb6YrzP+odtwYpCWyz6llg3Uu7qCpCYvhAbpywm7JQCmMXV0Li+AGL7fW0hfD10hMvBwM2ZJCL1g/58GFM0K0QBee+LQ5588j0ANFXxJh/KMMWtsQFUv/2jJdWYIWm396eaH3OSwosa+6t+yhr/uxDss6/mxPBJxXPsornRxrvfxhCXvLMqLXeHFzpwB0atbdwtu4NfyB6TzAMphkGkLCc7TT9+bE2e3rAQ6HP9rajcIeMM7EnlJjYlni77h+xOQPvyGF44UZZNTBgj1FPYMVN6kDGfGxYV9nxL8A/fcYa7HQTPvkQJ+hdR+9RoOHReOCPvqfSzwZKQq9v1X1h/hEhTC3Ig7UCqTdfu3HEUQf9qsJL/uJtRKUk8fDHlcLkJLBYJ773XAskRTs/3AyK7tjppFhBz6AsaI2v3DGgmVkOnbB2jNIcdtOlPoECzkpIIqCaAN9rovOroqpKAb7DTFr8pU4qMErFG6WuyLVjwC0zg1Sf58=
