language: python
before_script:
  - chmod +x semantic_release.sh && ./semantic_release.sh
script:
  - chmod +x build.sh && ./build.sh
  - chmod +x assets_release.sh && ./assets_release.sh
deploy:
  skip_cleanup: true
  provider: packagecloud
  repository: "develop"
  username: "twine"
  token:
    secure: "${PACKAGECLOUD_TOKEN}"
  dist: "python"
  local-dir: src/dist
  on:
    all_branches: true
after_deploy:
  skip_cleanup: true
  provider: script

env:
  global:
      secure: ZHo73saF9MNNy93eBVud/MACLOcRQFlzDSaTUfefcRy29b0pfP90tIeDjLyxPmKucgV8f+uDFIbsSNje+7XnskNuBtR3muWiwwcyTVJssDGjbCgEwCj/GdEy2AyUxjSN4JjBsJvYUS0QOcmmkx1ffQ2P8YorgGDBWpnqzNgO1sMBvSQCh/m7+59hwR8Ypv33SM4w5RqhC4mghZuMj3MAA4Is4/ZGjJdEeSctjmGy629tz4Xr0lpmdYeOD0EvnS2Fs725guTIctPD/MvLAEwB2NVrmxFyNxth5xWfX0qz9xXGv9AuWEny2wC5lZTXDY85SS2DBWmzpnKJHc6vfNhowaav+lczTT26MwobAl5Q9qqX3dBNMMK/zAJFz0TdCcqeFDvZc9OaC2EGUViRaIAUIl1BvpEqvxVB+wIvMnd60LdImLRZJzZ+mK/cVgKBLlBDdhlYQc99nT5yFGKpoF4pAz4QTcVS4Azl7zydBZWcnE9wjeG3ExxqOX1HRkbEhUlFm+vf0E4Hs95vo9lBCiVHmD12dEx792fZIce7zDoslvohcR9cxCHFRJLsUd3a8zl6gXJAsiColHaE8GYw/zmLqN5ls0kT5e6HeKKeIruBt/M+/mamPRxD70mih+2WhgrxnyX6gnh2DG95Xh/FLaWEx3TXBXOC82umOI4GnQHHOrE=
      secure: P5zH/ucWkxMxULonEqCQKxDIFV2Q24VCWsxdOSDQHpSv5BIIWuMLaKK6QO6vI7cxA08bCDS4k86lk+3ujbyAYvF6bespQpgjF5rHJ5X9wf5XQY5p7dcBZZ9PGjDnQnzyqzRq9cTe3v6XKz92gh7dxSZcgyKGJmRM52n5c0rZwzsT7an8Bn6AFPgpXxyLKSzlFZnbcYga56pIKGrRjOYhCXu0qrxBpF3MeTgqaJOBM/TIt2vE97/lDZh7X+wQWuCclY+t8HcVQQbRWg1TpyFLNtJKUEVpOMXivgmFm+x5jQGWCygt7Caeu4Es2Bq7Ur1YDqmdYIBQKzD6B12IwCObSLwVXMsxWecCFV7Why+yUm0UpDsv5ULjj/El3MsuQ12o1Hu4cmOerUgKKSJ5qsh7JufhIT0P8EtIz+QDtFK0nGjlXG/3FICdnDQJPtHEmvwglweVXShZIzYDBzwKAVhXYUCtNEeG+d5dM2n2mJYapfeJv2aafhBnXLb8+K6ecLfda/KLbRK8s5/pd95ggXvqy8e4RE5A5bKsno48dh7XIiJCRwU6LXxvKu+If8aDDdSeWWwwFcEcL/h7+DPmawLmqpqIFhK6/RjLjqvvHSF01oEIuDijcptUp/2SeZj4z3BPnETnbHd6F4YQmTAye2MWAB3pUWDiQAGK5ENeNUa6zoM=
